### ISSUE TITLE
lazyList fails on init in vim 7.3-429

### ISSUE THREAD

**Issue by javier-lopez** [KabbAmine/lazyList.vim#3]
Hello,

Thank you for lazyList, I've been trying to test the plugin but it fails with the following message when I try `:Lazylist` over sample text

```
item
item|
item
:LazyList
```

```
Error detected while processing function lazyList#New..<SNR>44_Init:                                                                       
line    1:
E716: Key not present in Dictionary: getIndexList()
E15: Invalid expression: self.getIndexList()
E716: Key not present in Dictionary: getIndexList()
E15: Invalid expression: self.getIndexList()
E117: Unknown function: s:Init
```

My vimrc file looks like this:

```
    Bundle 'KabbAmine/lazyList.vim'
        nnoremap gll :LazyList<CR>
        vnoremap gll :LazyList<CR>
        nnoremap gl* :LazyList '* '<CR>
        nnoremap gl* :LazyList '* '<CR>
```

I'm running vim 7.3 in Ubuntu 12.04

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:21:49)
Included patches: 1-429
```

**Comment by KabbAmine** [comment]
I can not reproduce the issue. IMO its related to the vim's version, but I can not find in what exactly.

If possible, try in vim 7.4>= and for me, I'll test in a virtual machine with ubuntu 12.04 when I'll have time.

**Comment by javier-lopez** [comment]
I tested in vim 7.4 and it works as expected, took some debugging messages

vim 7.3

```
calling function lazyList#New(1, 5)
line 1:
line 2: ^Ilet l:index = exists('a:1') ? a:1 : ''
line 3:
line 4: ^Ireturn { 'indexList'    : [], 'outputList'   : [], 'init'         : function('s:Init'), 'toggle'       : function('s:ToggleList'), 'getIndexList' : function('s:GetIndexList'), 'selecti
on'    : ll#selection#New(a:start, a:end).init(), 'index'        : ll#index#New(l:index).init() }
calling function lazyList#New..ll#selection#New(1, 5)
line 1:
line 2: ^Ireturn { 'start' : a:start, 'end'   : a:end, 'lines' : a:end - a:start + 1, 'list'  : [], 'init'  : function('s:Init'), 'get'   : function('s:Get') }
function lazyList#New..ll#selection#New returning {'list': [], 'init': function('s:Init...5, 'get': function('s:Get'), 'start': 1}
continuing in function lazyList#New
calling function lazyList#New..<SNR>25_Init()
line 1: ^Ilet self.indexList = self.getIndexList()
```

vim 7.4

```
calling function lazyList#New(1, 5)
line 1:
line 2: ^Ilet l:index = exists('a:1') ? a:1 : ''
line 3:
line 4: ^Ireturn { 'indexList'    : [], 'outputList'   : [], 'init'         : function('s:Init'), 'toggle'       : function('s:ToggleList'), 'getIndexList' : function('s:GetIndexList'), 'selecti
on'    : ll#selection#New(a:start, a:end).init(), 'index'        : ll#index#New(l:index).init() }
calling function lazyList#New..ll#selection#New(1, 5)
line 1:
line 2: ^Ireturn { 'start' : a:start, 'end'   : a:end, 'lines' : a:end - a:start + 1, 'list'  : [], 'init'  : function('s:Init'), 'get'   : function('s:Get') }
function lazyList#New..ll#selection#New returning {'list': [], 'init': function('<SNR>2...t': function('<SNR>26_Get'), 'start': 1}
continuing in function lazyList#New
calling function lazyList#New..<SNR>26_Init()
line 1: ^Icall self.get()
```

It looks to me than in vim 7.3 the function `lazyList#New..ll#selection#New` tries to execute the parent s.init function, which fails because it's too soon for it.

```
{'list': [], 'init': function('s:Init...5, 'get': function('s:Get'), 'start': 1}
line 1: ^Ilet self.indexList = self.getIndexList()
```

While in vim 7.4 it executes the local s:init function

```
{'list': [], 'init': function('<SNR>2...t': function('<SNR>26_Get'), 'start': 1}
line 1: ^Icall self.get()
```

Not sure if that's because of non named dictionaries, or different behavior in s:functions between vim 7.3 and 7.4.

I was able to run lazyList on vim 7.3 by renaming `s:Init` and `s:Get` to `a:Init`, `a:Get` in **ll/selection.vim**,  `b:Init`, `b:Get` in **ll/index.vim** and `c:Init`,  `c:Get` in **lazyList.vim** so vim doesn't get confused when selecting the appropriated Init/Get functions. That's of course just a hack, probably you'll know the correct syntax.

**Comment by KabbAmine** [comment]
Good catch :+1: , the scope of the methods is badly interpreted in vim 7.3 (I had the same result with vim 7.3.547 in my vagrant box).

`a:`, `b:` and `c:` in our case doesn't mean anything :smile: (`c:` in vimscript doesn't exist), so I'll investigate more and come up with a fix soon.

Thanks for your debugging, it helped me a lot.

**Comment by KabbAmine** [comment]
Should be good with 9056641

I'm not sure that I want to integrate those changes in the main branch, so until I decide please use the [fix-vim73 branch](https://github.com/KabbAmine/lazyList.vim/tree/fix-vim73).

@chilicuil I'll wait for your feedback before closing the issue.

**Comment by javier-lopez** [comment]
Hi @KabbAmine,

Thank you for the fix, that almost work =), in the file `autoload/lazyList.vim` there is a typo, it should be `lazyList#Init` and `lazyList#ToggleList` instead of `lazylist#Init` and `lazylist#ToggleList`

**Comment by KabbAmine** [comment]
Force pushed.
Thanks for reporting it.

**Comment by KabbAmine** [comment]
It works well on vim `7.3.547`, so issue closed.
@chilicuil Feel free to open it again if needed.
